### ISSUE TITLE
Broken links for Reference Brick Models

### ISSUE THREAD

**Issue by ar-chad** [BrickSchema/brick-website#162]
**Describe the bug**
Attempt to download any of the Brick Reference Models fails with 404. I tried

https://brickschema.org/ttl/soda_brick.ttl
https://brickschema.org/ttl/ghc_brick.ttl
https://brickschema.org/ttl/rice_brick.ttl
(https://brickschema.org/ttl/gtc_brick.ttl

**To Reproduce**
1. Go to 'https://brickschema.org/resources/'
2. Click on any of the following listed under Reference Brick Models: '[Soda Hall](https://brickschema.org/ttl/soda_brick.ttl)', '[Gates Hillman Center](https://brickschema.org/ttl/ghc_brick.ttl)', '[Rice Hall](https://brickschema.org/ttl/rice_brick.ttl)', '[Engineering Building Unit 3B](https://brickschema.org/ttl/ebu3b_brick.ttl)', '[Green Tech House](https://brickschema.org/ttl/gtc_brick.ttl)'
3. See error 404

**Expected behavior**
It would be expected to download or view the files in the browser.

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any
 - Version: any

**Comment by gtfierro** [comment]
@ar-chad I have pushed new reference models to https://brickschema.org/resources (see under [mortardata](https://brickschema.org/resources/#mortardata-brick-models)). For your reference, the https://github.com/BrickSchema/newsite repo tracks development of the new Brick site. I've also updated our description to note that the original 5 buildings no longer reflect best-practices. We retain them for historical reference. Let me know if you have any other questions!

**Comment by ar-chad** [comment]
@gtfierro thank you for a quick resolution of this. Now it is much clearer.

I also encountered issue with loading Brick.ttl 1.4.1 in Protege

At some point it can't resolve import:
![Screenshot 2024-09-10 at 15 56 52](https://github.com/user-attachments/assets/fe461a3c-edcd-4953-a596-f8ce91b701ce)

And after that fails with an error:
![Screenshot 2024-09-10 at 15 58 06](https://github.com/user-attachments/assets/cc8eb43a-45a3-42ef-a122-1bf76ee72f88)

Stack trace of the error is bellow:

Ontology already exists. OntologyID(OntologyIRI(<http://qudt.org/2.1/vocab/dimensionvector>) VersionIRI(<null>))


Full Stack Trace
-----------------------------------------------------------------------------------------

org.semanticweb.owlapi.model.OWLOntologyAlreadyExistsException: Ontology already exists. OntologyID(OntologyIRI(<http://qudt.org/2.1/vocab/dimensionvector>) VersionIRI(<null>))
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1253)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:1200)
	at org.protege.editor.owl.model.io.OntologyLoader.loadOntologyInternal(OntologyLoader.java:124)
	at org.protege.editor.owl.model.io.OntologyLoader.lambda$loadOntologyInOtherThread$0(OntologyLoader.java:71)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.semanticweb.owlapi.model.OWLOntologyRenameException: Could not rename ontology. An ontology with this ID already exists: OntologyID(OntologyIRI(<http://qudt.org/2.1/vocab/dimensionvector>) VersionIRI(<null>)) change: SetOntologyIDData(OntologyID(OntologyIRI(<http://qudt.org/2.1/vocab/dimensionvector>) VersionIRI(<null>)))
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.checkForOntologyIDChange(OWLOntologyManagerImpl.java:882)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.enactChangeApplication(OWLOntologyManagerImpl.java:642)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.applyChanges(OWLOntologyManagerImpl.java:670)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.applyChange(OWLOntologyManagerImpl.java:820)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer.applyChange(OWLRDFConsumer.java:733)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer.chooseAndSetOntologyIRI(OWLRDFConsumer.java:1492)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer.endModel(OWLRDFConsumer.java:1393)
	at org.semanticweb.owlapi.rio.RioOWLRDFConsumerAdapter.endRDF(RioOWLRDFConsumerAdapter.java:78)
	at org.semanticweb.owlapi.rio.RioParserImpl$RioParserRDFHandler.endRDF(RioParserImpl.java:300)
	at org.eclipse.rdf4j.rio.turtle.TurtleParser.parse(TurtleParser.java:170)
	at org.eclipse.rdf4j.rio.turtle.TurtleParser.parse(TurtleParser.java:125)
	at org.semanticweb.owlapi.rio.RioParserImpl.parseDocumentSource(RioParserImpl.java:245)
	at org.semanticweb.owlapi.rio.RioParserImpl.parse(RioParserImpl.java:185)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:220)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1303)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1243)
	... 7 more

**Comment by gtfierro** [comment]
The missing `ref` ontology will be fixed in the future, but for now, it shouldn't affect your usage much. I do not know why that Protege error is occurring though. Do you mind filing this issue on the main [Brick repo](https://github.com/brickschema/brick)?

**Comment by ar-chad** [comment]
Sure, I actually thought about posting it there in the first place. I'll post it later there. It looks like some dependency can't be downloaded. And it is a dependency of a dependency.
